### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by HydrolienF** [The-SourceCode/Advanced_Bukkit#2]
Can you add a gradle script to include dependencies? Or a README that list the dependencies.
I can't find from where you get "import net.minecraft.server.v1_11_R1.World;"

**Comment by Nopro263** [comment]
That is part of NMS (net.minecraft.server), you only get it by using your server software as a library. This is the obfuscated minecraft source code and you are not allowed to publish it. Search a tutorial on how to install nms for your minecraft version and possibly also how to install the mojang-mappings.

**Comment by HydrolienF** [comment]
Other plugins that use NMS include paper dependencies in a `build.gradle.kts` like that
```kotlin
dependencies {
    compileOnly("io.papermc.paper:paper-api:1.21.1-R0.1-SNAPSHOT")
}
```

**Comment by Nopro263** [comment]
I agree, but it seems that this repository is only used, so you don't have to write everything from the tutorials by hand.

Also the import for nms is really straightforward, you just have to change the version and get the correct file

**Comment by HydrolienF** [comment]
When I started Minecraft plugin devs in 2023, it wasn't easy to find for me.
I found other code examples that where working out of the box.
Thanks anyways.
